services:
  ecommerce_db:
    build:
      context: .
      dockerfile: Dockerfile
    image: ankane/pgvector:latest
    container_name: ecommerce_db
    restart: always
    shm_size: 128mb
    networks:
      - yesnetwork
    ports:
      - "7432:5432"
    volumes:
      - ecommerce_db_volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: wjdekdp9 # must change your own password.
      POSTGRES_USER: postgres # should change your own user name.

networks:
  yesnetwork:
    external: true

volumes:
  ecommerce_db_volume:
    name: ecommerce_db_volume
